// default package
// Generated 24 mars 2025, 21:05:34 by Hibernate Tools 5.1.2.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Classe generated by hbm2java
 */
public class Classe  implements java.io.Serializable {


     private int id;
     private Niveau niveau;
     private String nom;
     private Set affectationProfesseurs = new HashSet(0);
     private Set eleves = new HashSet(0);

    public Classe() {
    }

	
    public Classe(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Classe(int id, Niveau niveau, String nom, Set affectationProfesseurs, Set eleves) {
       this.id = id;
       this.niveau = niveau;
       this.nom = nom;
       this.affectationProfesseurs = affectationProfesseurs;
       this.eleves = eleves;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Niveau getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Niveau niveau) {
        this.niveau = niveau;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getAffectationProfesseurs() {
        return this.affectationProfesseurs;
    }
    
    public void setAffectationProfesseurs(Set affectationProfesseurs) {
        this.affectationProfesseurs = affectationProfesseurs;
    }
    public Set getEleves() {
        return this.eleves;
    }
    
    public void setEleves(Set eleves) {
        this.eleves = eleves;
    }




}


