// default package
// Generated 24 mars 2025, 21:05:34 by Hibernate Tools 5.1.2.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Eleve generated by hbm2java
 */
public class Eleve  implements java.io.Serializable {


     private int id;
     private Classe classe;
     private String nom;
     private String prenom;
     private Set parents = new HashSet(0);
     private Set notes = new HashSet(0);
     private Set appreciations = new HashSet(0);

    public Eleve() {
    }

	
    public Eleve(int id, String nom, String prenom) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
    }
    public Eleve(int id, Classe classe, String nom, String prenom, Set parents, Set notes, Set appreciations) {
       this.id = id;
       this.classe = classe;
       this.nom = nom;
       this.prenom = prenom;
       this.parents = parents;
       this.notes = notes;
       this.appreciations = appreciations;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Set getParents() {
        return this.parents;
    }
    
    public void setParents(Set parents) {
        this.parents = parents;
    }
    public Set getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set notes) {
        this.notes = notes;
    }
    public Set getAppreciations() {
        return this.appreciations;
    }
    
    public void setAppreciations(Set appreciations) {
        this.appreciations = appreciations;
    }




}


