// default package
// Generated 24 mars 2025, 21:05:34 by Hibernate Tools 5.1.2.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Matiere generated by hbm2java
 */
public class Matiere  implements java.io.Serializable {


     private int id;
     private String nom;
     private String description;
     private Set appreciations = new HashSet(0);
     private Set notes = new HashSet(0);
     private Set affectationProfesseurs = new HashSet(0);

    public Matiere() {
    }

	
    public Matiere(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Matiere(int id, String nom, String description, Set appreciations, Set notes, Set affectationProfesseurs) {
       this.id = id;
       this.nom = nom;
       this.description = description;
       this.appreciations = appreciations;
       this.notes = notes;
       this.affectationProfesseurs = affectationProfesseurs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getAppreciations() {
        return this.appreciations;
    }
    
    public void setAppreciations(Set appreciations) {
        this.appreciations = appreciations;
    }
    public Set getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set notes) {
        this.notes = notes;
    }
    public Set getAffectationProfesseurs() {
        return this.affectationProfesseurs;
    }
    
    public void setAffectationProfesseurs(Set affectationProfesseurs) {
        this.affectationProfesseurs = affectationProfesseurs;
    }




}


