// default package
// Generated 24 mars 2025, 21:05:34 by Hibernate Tools 5.1.2.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Niveau generated by hbm2java
 */
public class Niveau  implements java.io.Serializable {


     private int id;
     private String nom;
     private Set classes = new HashSet(0);

    public Niveau() {
    }

	
    public Niveau(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Niveau(int id, String nom, Set classes) {
       this.id = id;
       this.nom = nom;
       this.classes = classes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set classes) {
        this.classes = classes;
    }




}


