// default package
// Generated 24 mars 2025, 21:05:34 by Hibernate Tools 5.1.2.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Parent generated by hbm2java
 */
public class Parent  implements java.io.Serializable {


     private int id;
     private String nom;
     private String prenom;
     private String email;
     private Set eleves = new HashSet(0);

    public Parent() {
    }

	
    public Parent(int id, String nom, String prenom, String email) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.email = email;
    }
    public Parent(int id, String nom, String prenom, String email, Set eleves) {
       this.id = id;
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.eleves = eleves;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getEleves() {
        return this.eleves;
    }
    
    public void setEleves(Set eleves) {
        this.eleves = eleves;
    }




}


